drivers:mfd:max7729: Remove unused integer from freeze and restore.
../drivers/mfd/maxim/max77729.c:1020:6: error: unused variable 'i' [-Werror,-Wunused-variable]
        int i;
            ^
../drivers/mfd/maxim/max77729.c:1031:6: error: unused variable 'i' [-Werror,-Wunused-variable]
        int i;

Change-Id: Ic75a6d7cf169e7104495a9fd32958e1e16e5c7f2
Signed-off-by: muralivijay <muralidharan9845@gmail.com>
Signed-off-by: GuidixX <guidixm@gmail.com>