drivers:usb:max77729: Guard  EXTCON_PROP_USB_TYPEC_MED_HIGH_CURRENT with Linux version.
* Linux 5.15 never use this prop.
* So Guard it with Linux version.

error: use of undeclared identifier 'EXTCON_PROP_USB_TYPEC_MED_HIGH_CURRENT'

This reverts commit be357a416e4cd3e06a0344100431409c49023782.

Change-Id: I045f14aa193819358a435c2371c877ae20af175b
Signed-off-by: muralivijay <muralidharan9845@gmail.com>
Signed-off-by: GuidixX <guidixm@gmail.com>