include: fix pmic-voter redefination error.
* max77729_usbc header should use pmic-voter header from nopmi . instead from linux . for avoid conflicts.

error:
../drivers/power/supply/nopmi/qcom-pmic-voter.h:14:6: error: redefinition of 'votable_type'
enum votable_type {
     ^
../include/linux/pmic-voter.h:14:6: note: previous definition is here
enum votable_type {
     ^
In file included from ../drivers/power/supply/pd_policy_manager.c:17:
In file included from ../drivers/power/supply/pd_policy_manager.h:19:
../drivers/power/supply/nopmi/qcom-pmic-voter.h:15:2: error: redefinition of enumerator 'VOTE_MIN'
        VOTE_MIN,
        ^
../include/linux/pmic-voter.h:15:2: note: previous definition is here
        VOTE_MIN,
        ^
In file included from ../drivers/power/supply/pd_policy_manager.c:17:
In file included from ../drivers/power/supply/pd_policy_manager.h:19:
../drivers/power/supply/nopmi/qcom-pmic-voter.h:16:2: error: redefinition of enumerator 'VOTE_MAX'
        VOTE_MAX,
        ^
../include/linux/pmic-voter.h:16:2: note: previous definition is here
        VOTE_MAX,
        ^
In file included from ../drivers/power/supply/pd_policy_manager.c:17:
In file included from ../drivers/power/supply/pd_policy_manager.h:19:
../drivers/power/supply/nopmi/qcom-pmic-voter.h:17:2: error: redefinition of enumerator 'VOTE_SET_ANY'
        VOTE_SET_ANY,
        ^
../include/linux/pmic-voter.h:17:2: note: previous definition is here
        VOTE_SET_ANY,
        ^
In file included from ../drivers/power/supply/pd_policy_manager.c:17:
In file included from ../drivers/power/supply/pd_policy_manager.h:19:
../drivers/power/supply/nopmi/qcom-pmic-voter.h:18:2: error: redefinition of enumerator 'NUM_VOTABLE_TYPES'
        NUM_VOTABLE_TYPES,
        ^
../include/linux/pmic-voter.h:18:2: note: previous definition is here
        NUM_VOTABLE_TYPES,
        ^

Change-Id: I228946c43b41d432a1622b0aed5dbaf2e3482bcb
Signed-off-by: muralivijay <muralidharan9845@gmail.com>
Signed-off-by: GuidixX <guidixm@gmail.com>